### ISSUE TITLE
关于您博客文章《python验证码识别4:滴水算法分割图片》中代码的疑问

### ISSUE THREAD

**Issue by luoyanhan** [shenyushun/data_captchar#1]
代码96 和 100 行的是否应该使用last_p[0]来判断水滴惯性方向?因为看您的代码66,67行在每次循环都会将next_x设置为当前点的x坐标，用next_x判断惯性的话会不会无法触发那两个if判断？

**Comment by shenyushun** [comment]
@luoyanhan   多谢指正，确实如你所说。一年前写这篇博客时候滴水算法也是初学，后来看完原始论文后博客忘改了。
